###################################################################################
#                                Snakefile                                        #
#                         MSc. Matheus Cosentino                                  # 
###################################################################################
#                                                                                 #
# oooooooooo.    o8o                               oooooo     oooo  o8o           #
# `888'   `Y8b   `"'                                `888.     .8'   `"'           #
#  888      888 oooo   .oooo.o  .ooooo.   .ooooo.    `888.   .8'   oooo  oooo d8b #
#  888      888 `888  d88(  "8 d88' `"Y8 d88' `88b    `888. .8'    `888  `888""8P #
#  888      888  888  `"Y88b.  888       888   888     `888.8'      888   888     #
#  888     d88'  888  o.  )88b 888   .o8 888   888      `888'       888   888     #
# o888bood8P'   o888o 8""888P' `Y8bod8P' `Y8bod8P'       `8'       o888o d888b    #
#                                                                                 #
###################################################################################
#                              version: 12.2025                                   #
###################################################################################
                                                                               
 
##################################
# --- 1. Load Configuration --- #
#################################
#configfile: "config/config.yaml"

###########################################
# --- 2. Import functions to be used --- #
##########################################
import os
import ast 
from glob import glob
from scripts.functions import get_final_outputs
from scripts.functions import cleanup_downloaded_fastqs
from scripts.functions import filter_nohits
from scripts.functions import identify_data_type
from scripts.functions import get_input_r1
from scripts.functions import get_input_r2
from scripts.functions import get_input_unp
from scripts.functions import get_contigs_path
from scripts.functions import get_denovo_r1
from scripts.functions import get_denovo_r2
from scripts.functions import get_denovo_unpaired
from scripts.functions import get_ONP_input
from scripts.functions import get_spades_params
from scripts.functions import get_megahit_params
from scripts.functions import get_sra_layout
from scripts.functions import get_diamond_db_input
from scripts.functions import get_diamond_db_name
from scripts.functions import get_header_check
from scripts.functions import get_multiqc_inputs


###########################################################
# --- 3. Define workflown directory and local infos  --- #
##########################################################
DATA = config["data_dir"]
OUT_DIR = config["output_dir"]

with open(config["sample_list"], "r") as file:
    SAMPLE = [line.strip() for line in file if line.strip()]

SAMPLE_META = identify_data_type(SAMPLE, DATA)

############################################
# --- 4. Export functions to be used.  --- #
###########################################
import scripts.functions as functions

if isinstance(config["modules"], str):
    try:
        config["modules"] = ast.literal_eval(config["modules"])
    except (ValueError, SyntaxError):
        print("[ERROR] Could not parse 'modules' configuration string.")
        raise

functions.DATA = DATA
functions.SAMPLE = SAMPLE
functions.OUT_DIR = OUT_DIR
functions.SAMPLE_META = SAMPLE_META
functions.MAPPER = config["tool"]["denovo"] 
functions.MODULES = config["modules"]
functions.get_final_outputs = get_final_outputs
functions.cleanup_downloaded_fastqs = cleanup_downloaded_fastqs
functions.filter_nohits = filter_nohits
functions.identify_data_type = identify_data_type
functions.get_input_r1 = get_input_r1
functions.get_input_r2 = get_input_r2
functions.get_input_unp = get_input_unp
functions.get_contigs_path = get_contigs_path
functions.get_denovo_r1 = get_denovo_r1
functions.get_denovo_r2 = get_denovo_r2
functions.get_denovo_unpaired = get_denovo_unpaired
functions.get_ONP_input = get_ONP_input
functions.get_spades_params = get_spades_params
functions.get_megahit_params = get_megahit_params
functions.get_sra_layout = get_sra_layout
functions.get_header_check = get_header_check
functions.get_multiqc_inputs = get_multiqc_inputs 

##############################################
# --- 5. Define Conda Environment Paths --- #
#############################################

DOWNLOAD = workflow.source_path(config["envs"]["download"])
FASTP = workflow.source_path(config["envs"]["fastp"])
DENOVO = workflow.source_path(config["envs"]["denovo"])
DIAMOND = workflow.source_path(config["envs"]["diamond"])
KRAKEN2= workflow.source_path(config["envs"]["kraken2"])
KRAKEN2_BIOM= workflow.source_path(config["envs"]["kraken2_biom"])
TAXONKIT = workflow.source_path(config["envs"]["taxonkit"])
CORE = workflow.source_path(config["envs"]["core"])
REPORT = workflow.source_path(config["envs"]["report"])
PALM = workflow.source_path(config["envs"]["palm_annot"])
MULTIQC = workflow.source_path(config["envs"]["multiqc"])


#################################
# --- 6. Define Parameters --- #
################################

FASTP_PAR = config['fastp']
SPADES = config['spades']
FLYE = config['flye']
DIAMOND_PAR = config['diamond']
KRAKEN2_PAR = config['kraken2']
PALM_ANNOT = config['palm_annot']


#######################################
# --- 7. Load the Workflow Rules --- #
######################################

include: "rules/get_data.smk"
include: "rules/fastp.smk"
include: "rules/denovo.smk"
include: "rules/diamond.smk"
include: "rules/kraken2.smk"
include: "rules/lineage.smk"
include: "rules/duskmatter.smk"
include: "rules/reporting.smk"

###############################################################
# --- 8. Obtain the final target & Download Data cleanup --- #
##############################################################
rule all:
    input:
        # 1. The Aggregate Report
        os.path.join(OUT_DIR, "multiqc", "multiqc_report.html"),
        
        # 2. The Per-Sample Reports (Expanded for all samples)
        expand(os.path.join(OUT_DIR, "{sample}", "multiqc", "multiqc_report.html"), sample=SAMPLE)

onsuccess:
    cleanup_downloaded_fastqs()
    print("Workflow finished successfully!")

onerror:
    print("Workflow failed. Temporary files were NOT removed to aid debugging.")