###################################################################################
# Snakefile
#MSc. Matheus Cosentino 
###################################################################################
# oooooooooo.    o8o                               oooooo     oooo  o8o           #
# `888'   `Y8b   `"'                                `888.     .8'   `"'           #
#  888      888 oooo   .oooo.o  .ooooo.   .ooooo.    `888.   .8'   oooo  oooo d8b #
#  888      888 `888  d88(  "8 d88' `"Y8 d88' `88b    `888. .8'    `888  `888""8P #
#  888      888  888  `"Y88b.  888       888   888     `888.8'      888   888     #
#  888     d88'  888  o.  )88b 888   .o8 888   888      `888'       888   888     #
# o888bood8P'   o888o 8""888P' `Y8bod8P' `Y8bod8P'       `8'       o888o d888b    #

###################################################################################
# version: 12.2025
###################################################################################
                                                                               
 
##################################
# --- 1. Load Configuration --- #
#################################
configfile: "config/config.yaml"

###########################################
# --- 2. Import functions to be used --- #
##########################################
import os
from glob import glob
from scripts.functions import get_final_outputs
from scripts.functions import cleanup_downloaded_fastqs
from scripts.functions import identify_data_type

###########################################################
# --- 3. Define workflown directory and local infos  --- #
##########################################################
DATA = config["data_dir"]
SAMPLE = config["sample_list"]
SAMPLE_META = identify_data_type(DATA, SAMPLE_META)

###############################################
# --- 4. Define Global Environment Paths --- #
##############################################

DOWNLOAD = workflow.source_path(config["envs"]["download"])
FASTP = workflow.source_path(config["envs"]["fastp"])
DENOVO = workflow.source_path(config["envs"]["denovo"])
DIAMOND = workflow.source_path(config["envs"]["diamond"])
TAXONKIT = workflow.source_path(config["envs"]["taxonkit"])
SCRIPTS = workflow.source_path(config["envs"]["scripts"])
REPORT = workflow.source_path(config["envs"]["report"])
PALM = workflow.source_path(config["envs"]["palm_annot"])

#######################################
# --- 5. Load the Workflow Rules --- #
######################################

include: "workflow/rules/get_data.smk"
include: "workflow/rules/fastp.smk"
include: "workflow/rules/spades.smk"
include: "workflow/rules/diamond.smk"
include: "workflow/rules/lineage.smk"
include: "workflow/rules/reporting.smk"
include: "workflow/rules/duskmatter.smk"

###############################################################
# --- 6. Obtain the final target & Download Data cleanup --- #
##############################################################
rule all:
    input: get_final_outputs

onsuccess:
    cleanup_downloaded_fastqs(log)
    print("Workflow finished successfully!")

onerror:
    print("Workflow failed. Temporary files were NOT removed to aid debugging.")