{% set name = "discovir" %}
{% set version = "1.0.1-beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# O Bioconda não constrói a partir de diretórios locais. Eles puxam via URL.
# Para testar a receita *LOCALMENTE* antes de abrir um PR, descomente o bloco "path" e comente o "url/sha256".
# Ao abrir o Pull Request oficial, utilize APENAS o bloco de "url" e o "sha".
source:
  #path: ..
  url: "https://github.com/matheus-cosentino/discovir/releases/tag/v{{ version }}/discovir-{{ version }}.tar.gz"
  sha256: "4067da96cbe2de92d9a2b6fbbb7e3994404569455c3c61b4e5671b792705b96e"



build:
  number: 0
  noarch: generic

requirements:
  host:
    - python >=3.8
  run:
    - bash
    - python >=3.8
    - snakemake >=9.11.1
    - snakemake-executor-plugin-slurm >=2.0.0
    - coreutils

test:
  commands:
    - discovir --help
    - discovir --version

about:
  home: "https://github.com/matheus-cosentino/discovir"
  license: "GPL-3.0-or-later"
  license_family: GPL
  license_file: LICENSE
  summary: "A Snakemake Pipeline for Integrated Viral Discovery."
