###################################################################################
#                               Config file                                       #
#                         MSc. Matheus Cosentino                                  # 
###################################################################################
#                                                                                 #
# oooooooooo.    o8o                               oooooo     oooo  o8o           #
# `888'   `Y8b   `"'                                `888.     .8'   `"'           #
#  888      888 oooo   .oooo.o  .ooooo.   .ooooo.    `888.   .8'   oooo  oooo d8b #
#  888      888 `888  d88(  "8 d88' `"Y8 d88' `88b    `888. .8'    `888  `888""8P #
#  888      888  888  `"Y88b.  888       888   888     `888.8'      888   888     #
#  888     d88'  888  o.  )88b 888   .o8 888   888      `888'       888   888     #
# o888bood8P'   o888o 8""888P' `Y8bod8P' `Y8bod8P'       `8'       o888o d888b    #
#                                                                                 #
###################################################################################
#                              version: 12.2025                                   #
###################################################################################
                                                                               
### Main output directory
output_dir: "results"

###Add path to directory of files of interest
data_dir: "data"

### File with sample names of interest to be wildcards of sample
sample_list: "accessions.txt"

### Modules of Analysis to be requested
modules: 
  keep_download: true  #Remove data download from SRA (default: false)
  assembly: true # Perform de novo assembly for reads (default: false)
  kraken2: true #Perform taxonomic assignment for Kraken2 (default: false)
  diamond: false #Perform taxonomic assignment for Diamond against nr5 for Reads(default: false)
  duskmatter: false #Perform palm annot identification (default: false)
  reads_kraken2: true #Perform reads taxonomic identification (default: false)
  reads_diamond: false #Perform reads taxonomic identification (default: false)


### De novo tools to be requested
tool:
  denovo: #'spades' # Select your favorite de novo assembly (default: 'spades')
  # options: 
  ##- 'spades'.    # more resourcers needed, but algorythis to better deal with RNA seq data (default)
  ##- 'megahit'    # faster, more error proner
  - 'flye'       #indicated for nanopore sequencing long reads

### Envs paths to be installed
envs:
  fastp: "envs/fastp.yaml"
  denovo: "envs/denovo.yaml"
  diamond: "envs/diamond.yaml"
  kraken2: "envs/kraken2.yaml"
  kraken2_biom: "envs/kraken2_biom.yaml"
  taxonkit: "envs/taxonkit.yaml"
  download: "envs/download.yaml"
  scripts: "envs/DiscoVir.yaml"
  report: "envs/report.yaml"
  palm_annot: "envs/palm_annot.yaml"

### databases and resources for the workflow
resources:
  diamond: "resources/ncbi/NCBI_2025_07_22.dmnd"
  kraken2: "resources/kraken2/database"
  taxonnodes: "resources/taxonomy/nodes.dmp"
  taxonnames: "resources/taxonomy/names.dmp"
  taxonmap: "resources/taxonomy/prot.accession2taxid.gz"
  palm_annot_dir: "resources/palm_annot"
  logo_dirs: "resources/logo/"


### Parameters for each tool used within the dataset ###
# QC
fastp:
  length_required: 15
  qualified_quality_phred: 30
  
# De Novo Assembly for Illumina reads
spades:
  algorithm : "--rnaviral" #low resources and correction of RNA artifacts assembly
  #algorithm: "--coronaspades" #indicate for genomic de novo assembly of CoV genomes by HMM guides
  #algorithm: "--meta" #high resources and identification of low coverage/presence virus

#De novo for long reads assembly data
flye: 
  #type: "pacbio-raw" #PacBio regular CLR reads (<20% error)
  #type: "pacbio-corr" #PacBio reads that were corrected with other methods (<3% error)
  #type: "pacbio-hifi" #PacBio HiFi reads (<1% error)
  #type: "nano-raw" #ONT regular reads, pre-Guppy5 (<20% error)
  type: "nano-corr" #ONT reads that were corrected with other methods (<3% error)
  #type: "nano-hq" #ONT high-quality reads: Guppy5+ SUP or Q20 (<5% error)

# Taxonomy by local alignment
diamond:
  outfmt: 6
  max_target_seqs: 1
  evalue: 0.00001
  sensitivity: "--very-sensitive"

# Taxonomy by k-mer iddentification
kraken2:
  confidence: 0.0 #   confidence score threshold (default: 0.0); must be in [0,1]

#  Dusk Matter Search
palm_annot: 
  seqtype: "aa" 
  minscore: 50
  minpssmscore: 10