###################################################################################
#                               Config file                                       #
#                         MSc. Matheus Cosentino                                  # 
###################################################################################
#                                                                                 #
# oooooooooo.    o8o                               oooooo     oooo  o8o           #
# `888'   `Y8b   `"'                                `888.     .8'   `"'           #
#  888      888 oooo   .oooo.o  .ooooo.   .ooooo.    `888.   .8'   oooo  oooo d8b #
#  888      888 `888  d88(  "8 d88' `"Y8 d88' `88b    `888. .8'    `888  `888""8P #
#  888      888  888  `"Y88b.  888       888   888     `888.8'      888   888     #
#  888     d88'  888  o.  )88b 888   .o8 888   888      `888'       888   888     #
# o888bood8P'   o888o 8""888P' `Y8bod8P' `Y8bod8P'       `8'       o888o d888b    #
#                                                                                 #
###################################################################################
#                              version: 12.2025                                   #
###################################################################################
                                                                               
### Main output directory
output_dir: "results"

###Add path to directory of files of interest
data_dir: "data"

### File with sample names of interest to be wildcards of sample
sample_list: "accessions.txt"

### Modules of Analysis to be requested
modules: 
  keep_download: true  #Remove data download from SRA (default: false)
  download_only: false #Only download data from SRA (default: false)
  assembly: true # Perform de novo assembly for reads (default: false)
  kraken2: true #Perform taxonomic assignment for Kraken2 (default: false)
  diamond: true #Perform taxonomic assignment for Diamond against nr5 for Reads(default: false)
  darkmatter: true #Perform palm annot identification (default: false)
  reads_kraken2: true #Perform reads taxonomic identification (default: false)
  reads_diamond: true #Perform reads taxonomic identification (default: false)
  basta: false #perform basta LCA Algo
  

### De novo tools to be requested
tool:
  denovo: #select your favorite de novo tools
  # options: 
    - 'spades'    # more resourcers needed, but algorythis to better deal with RNA seq data of Illumina short reads(default)
   #- 'megahit'    # indicated for llumina short reads. Faster, but more error proner
   # - 'flye'       #indicated for nanopore sequencing long reads (>1000 bp per reads)
   # - 'raven'      #indicated for nanopore sequencing. Faster, but more error proner
   # - 'medaka_flye'   #correction to ONP flye assembly
   # - 'medaka_raven'  #correction to ONP raven assembly
   
### Envs paths to be installed
envs:
  fastp: "envs/fastp.yaml"
  denovo: "envs/denovo.yaml"
  diamond: "envs/diamond.yaml"
  kraken2: "envs/kraken2.yaml"
  kraken2_biom: "envs/kraken2_biom.yaml"
  taxonkit: "envs/taxonkit.yaml"
  download: "envs/download.yaml"
  core: "envs/DiscoVir.yaml"
  report: "envs/report.yaml"
  palm_annot: "envs/palm_annot.yaml"
  multiqc: "envs/multiqc.yaml"
  spades: "envs/spades.yaml"
  basta: "envs/basta.yaml"
  krona: "envs/krona.yaml"
  r_rarefaction: "envs/r_rarefaction.yaml"


### databases and resources for the workflow
resources:
  diamond: 
  #diamond workflow used for the database
   - "resources/diamond" 
  #kraken2 folder with all the files
  kraken2: 
   - "resources/kraken2"
  # prot2taxid info
  taxonomy:
   - "resources/taxonomy"
  basta_db:
    - "resources/basta_db"
  #palm annot resources
  palm_annot_dir: 
    - "resources/palm_annot"
  #logos
  logo_dirs: 
    - "resources/logo/"
 #krona db
  krona: 
    - "resources/krona/taxonomy"

### Parameters for each tool used within the dataset ###

# QC
fastp:
  length_required: 
    - 50 #illlumina adapters expected
    #- 500 #nanopore conservative size for low reads
  qualified_quality_phred: 
    - 30 #illumina paired end
    #- 10 #long read
  
# De Novo Assembly for Illumina reads
spades:
  algorithm:
   #- '--isolate'     # Highly recommended for high-coverage isolate and multi-cell data
   #- '--sc'          # Required for MDA (single-cell) data
   - '--meta'        # Required for metagenomic data. Currently metaSPAdes supports only a single short-read library which has to be paired-end
   #- '--bio'         # Required for biosyntheticSPAdes mode
   #- '--corona'      # Required for coronaSPAdes mode, a special mode of rnaviralSPAdes specifically aimed for SARS-CoV-2 de novo assembly
   #- '--rna'         # Required for RNA-Seq data
   #- '--plasmid'     # Runs plasmidSPAdes, a pipeline for extracting and assembling plasmids from WGS data sets
   #- '--metaviral'   # Runs metaviralSPAdes pipeline for virus detection.
                      # These options works specially for extracting extrachromosomal elements from metagenomic assemblies.
                      # They run similar pipelines that slightly differ in the simplification step.
                      # Another difference is that for metaviral mode we output linear putative extrachromosomal contigs (unlike for metaplasmid mode).
   #- '--metaplasmid' # Runs metaplasmidSPAdes pipeline for plasmid detection in metagenomic datasets (equivalent for --meta --plasmid)
   #- '--rnaviral'    # Enables virus assembly with a de novo assembler tailored for RNA viral datasets (transcriptome, metatranscriptome and metavirome) 

  kmer:               # list of k-mer sizes, must be odd and less than 128 (Default: 21,33,55)
    - 'auto'          # SPAdes works by building de Bruijngraphs for several values of k. Let its “machine learning” choose the best values to use.
    #- '21'            # Minimum value
    #- '33'
    #- '127'           # Maximum value
    #- '111'           # Custom or your choice (https://www.chilimath.com/lessons/introductory-algebra/list-of-odd-numbers)
    #- '21_33'
    #- '21_33_55'   # If you have enough coverage (+50x), then you may want to try to set this k-mer lengths
    #- '21_33_55_77_99'
    #- '21_33_55_77_99_111'
    #- '21_33_55_77_99_111_127'

#De novo for long reads assembly data
flye: 
  #type: "pacbio-raw" #PacBio regular CLR reads (<20% error)
  #type: "pacbio-corr" #PacBio reads that were corrected with other methods (<3% error)
  #type: "pacbio-hifi" #PacBio HiFi reads (<1% error)
  #type: "nano-raw" #ONT regular reads, pre-Guppy5 (<20% error)
  type: "nano-corr" #ONT reads that were corrected with other methods (<3% error)
  #type: "nano-hq" #ONT high-quality reads: Guppy5+ SUP or Q20 (<5% error)

# Taxonomy by local alignment
diamond:
  outfmt: 
    #- 0 #BLAST pairwise
    #- 5 #BLAST XML
    - 6 #BLAST tabular (default)
    #- 100 #DIAMOND alignment archive (DAA)
    #- 101 #SAM
    #- 102 #Taxonomic classification
    #- 103 #PAF
    #- 104 #JSON (flat)

  max_target_seqs: 
    - 1
    #- 10
    #- 20
  
  evalue: 
    #- 0.00001
    #- 0.0001
    - 0.001
    #- 0.01

  sensitivity: 
    #- "--ultra-sensitive"
    #- "--very-sensitive"
    #- "--mid-sensitive"
    #- "--more-sensitive"
    - "--sensitive"


#LCA algorythim
basta:
  classification:
    #values between 51 and 99 BASTA returns the taxonomy that is shared by at least the given percentage of hits. 
    - 51    #percentage of best hits 51 (minimum)
    #- 75
    #- 99    
    #- 100 
  identity: #minimum id to diamond hit to consider to lca basta algorythim
    #- 30
    - 40
    #- 50
    #- 60
    #- 70
    #- 80 #basta default
    #- 90
    #- 100
  lengths: #minimum hit length of orf to be considered to basta lca algorythim
    - 30 #discovir default to calculate lca for small hits
    #- 40
    #- 50
    #- 60
    #- 70
    #- 80
    #- 90
    #- 100 #basta default
  min_hits: #minimum number of hits within a sequence to be considered to basta lca algorythim
    - 1
    #- 2
    #- 3 #basta default
    #- 4
    #- 5

# Taxonomy by k-mer iddentification
kraken2:
  confidence: 0.0 #   confidence score threshold (default: 0.0); must be in [0,1]

kraken_biom:
  format:
    #- "tsv"
    - "hdf5"
    #- "json"
  max:
    - "D"
    #- "P"
    #- "C"
    #- "O"
    #- "F"
    #- "G"
    #- "S"
    #- "SS"
  min: 
    #- "D"
    #- "P"
    #- "C"
    #- "O"
    - "F"
    #- "G"
    #- "S"
    #- "SS"

# Rarefaction Curve
rarefaction:
  tax_level: "Genus" # Taxonomic level for rarefaction (e.g., Family, Genus, Species)

#  Dark Matter Search
palm_annot: 
  seqtype: "aa" 
  minscore: 50
  minpssmscore: 10

# Medaka correction
# --> DEFINE O MODELO ATIVO AQUI:
medaka_model: "r941_min_sup_g507" 

# === R9.4.1 (Padrão Antigo / "Legacy") ===
# MinION / GridION
# - r941_min_sup_g507   (RECOMENDADO para R9)
# - r941_min_hac_g507
# - r941_min_fast_g507
# PromethION
# - r941_prom_sup_g507
# - r941_prom_hac_g507
# - r941_prom_fast_g507
