# Load Configuration
configfile: "config/workflow_config.yaml"

# Main output directory
output_dir: "results"

# Add path to SRA accessions of interest
sra_file: "sra_accessions.txt"

# --- Workflow Options ---
options:
  diversity_reads: false
  generate_report: false
  download_only: false
  palm_annot: true

# Envs with tools necessary to use
envs:
  fastp: "workflow/envs/fastp.yaml"
  spades: "workflow/envs/spades.yaml"
  diamond:  "workflow/envs/diamond.yaml"
  taxonkit: "workflow/envs/taxonkit.yaml"
  download: "workflow/envs/download.yaml"
  scripts: "workflow/envs/scripts.yaml"
  pandoc: "workflow/envs/pandoc.yaml"
  palm_annot: "workflow/envs/palm_annot.yaml"

db:
  diamond: "resources/database/NCBI_2025_07_22.dmnd"
  taxonnodes: "resources/database/nodes.dmp"
  taxonnames: "resources/database/names.dmp"
  taxonmap: "resources/database/prot.accession2taxid.gz"
  palm_annot_dir: "resources/palm_annot"

report:
  logo: "resources/report/DiscoVir.png"
  title: "DiscoVir Workflow Report"
  author: "Cosentino MAC/ UFRJ & IRD"

# Add a new section for rule-specific parameters
params:
  fastp:
    length_required: 15
    qualified_quality_phred: 30
  
  spades:
#    extra: "--meta"  
    extra: "--rnaviral"

  diamond:
    outfmt: 6
    max_target_seqs: 1
    evalue: 0.00001

  summary:
    rank: "family"
  
  palm_annot: 
    seqtype: "aa" 
    minscore: 50
    minpssmscore: 10
