###################################################################################
#                             Slurm Profile                                       #
#                         MSc. Matheus Cosentino                                  # 
###################################################################################
#                                                                                 #
# oooooooooo.    o8o                               oooooo     oooo  o8o           #
# `888'   `Y8b   `"'                                `888.     .8'   `"'           #
#  888      888 oooo   .oooo.o  .ooooo.   .ooooo.    `888.   .8'   oooo  oooo d8b #
#  888      888 `888  d88(  "8 d88' `"Y8 d88' `88b    `888. .8'    `888  `888""8P #
#  888      888  888  `"Y88b.  888       888   888     `888.8'      888   888     #
#  888     d88'  888  o.  )88b 888   .o8 888   888      `888'       888   888     #
# o888bood8P'   o888o 8""888P' `Y8bod8P' `Y8bod8P'       `8'       o888o d888b    #
#                                                                                 #
###################################################################################
#                              version: 03.2026                                   #
###################################################################################


############################
# --- 1. Slurm Params --- #
###########################

# cluster params, number of jobs to be ran simullteniously
jobs: 15

#snakemake params
executor: slurm
restart-times: 0
latency-wait: 600
keep-going: true
rerun-incomplete: true
use-conda: true
show-failed-logs: true

#######################################
# --- 2. Slurm Default Resources --- #
######################################

default-resources:
  tmpdir: /scr
  threads: 2
  mem_mb: 8000

#######################################
# --- 3. Slurm Specific Resources --- #
######################################
set-resources:
  spades:
    mem_mb: 60000
    threads: 12
    #slurm_partition: normal
  megahit:
    mem_mb: 60000
    threads: 12
    #slurm_partition: normal
  flye:
    mem_mb: 60000
    threads: 12
    #slurm_partition: normal
  diamond_blastx_contigs:
    mem_mb: 600000
    threads: 24
    #slurm_partition: normal
  diamond_blastx_reads:
    mem_mb: 600000
    threads: 24
    #slurm_partition: normal
  kraken2_contigs:
    mem_mb: 80000
    threads: 16
    #slurm_partition: normal
  kraken2_reads_unpaired:
    mem_mb: 80000
    threads: 16
    #slurm_partition: normal
  kraken2_reads_paired:
    mem_mb: 80000
    threads: 16
    #slurm_partition: normal
  map_accession_to_taxid:
    mem_mb: 60000
    threads: 12
  cd_hit:
    mem_mb: 16000
    threads: 4
  krona_update_taxonomy:
    mem_mb: 32000
    threads: 8

